version: "2.1"

volumes:
  plex:
  nzbget:
  sonarr:
  radarr:
  nzbhydra:
  duplicati:
  qbittorrent:

services:
  # https://hub.docker.com/r/linuxserver/plex
  plex:
    build:
      context: .
      dockerfile: Dockerfile.plex
    privileged: true
    network_mode: host
    volumes:
      - plex:/config
    environment:
      PUID: "1000"
      PGID: "1000"

  # https://hub.docker.com/r/linuxserver/nzbget
  nzbget:
    build:
      context: .
      dockerfile: Dockerfile.nzbget
    privileged: true
    ports:
      - 6789:6789/tcp
    volumes:
      - nzbget:/config
    environment:
      PUID: "1000"
      PGID: "1000"
  
  # https://hub.docker.com/r/linuxserver/qbittorrent      
  qbittorrent: 
    build:
      context: .
      dockerfile: Dockerfile.qbittorrent
    privileged: true
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    volumes:
      - qbittorrent:/config
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080


  # https://hub.docker.com/r/linuxserver/sonarr
  sonarr:
    build:
      context: .
      dockerfile: Dockerfile.sonarr
    privileged: true
    ports:
      - 8989:8989/tcp
    volumes:
      - sonarr:/config
    environment:
      PUID: "1000"
      PGID: "1000"
    depends_on:
      - nzbhydra
      - nzbget

  # https://hub.docker.com/r/linuxserver/radarr
  radarr:
    build:
      context: .
      dockerfile: Dockerfile.radarr
    privileged: true
    ports:
      - 7878:7878/tcp
    volumes:
      - radarr:/config
    environment:
      PUID: "1000"
      PGID: "1000"
    depends_on:
      - nzbhydra
      - nzbget

  # https://hub.docker.com/r/linuxserver/nzbhydra2
  nzbhydra:
    build:
      context: .
      dockerfile: Dockerfile.nzbhydra
    privileged: true
    ports:
      - 5076:5076/tcp
    volumes:
      - nzbhydra:/config
    environment:
      PUID: "1000"
      PGID: "1000"

  # https://hub.docker.com/r/linuxserver/duplicati
  duplicati:
    image: linuxserver/duplicati
    environment:
      PUID: "0"
      PGID: "0"
      CLI_ARGS: --webservice-interface=any
    ports:
      - 8200:8200/tcp
    volumes:
      - duplicati:/config
      - plex:/source/plex:ro
      - nzbget:/source/nzbget:ro
      - sonarr:/source/sonarr:ro
      - radarr:/source/radarr:ro
      - nzbhydra:/source/nzbhydra:ro
