version: '2.1'

volumes:

    plex_config:
    nzbget_config:
    sonarr_config:
    radarr_config:
    downloads:

services:

    # https://hub.docker.com/r/lsioarmhf/plex
    plex:
        image: lsioarmhf/plex
        network_mode: host
        volumes:
            - 'plex_config:/config'
            - 'downloads:/downloads'

    # https://hub.docker.com/r/lsioarmhf/nzbget
    nzbget:
        image: lsioarmhf/nzbget
        ports:
            - '6789:6789/tcp'
        volumes:
            - 'nzbget_config:/config'
            - 'downloads:/downloads'

    # https://hub.docker.com/r/lsioarmhf/sonarr
    sonarr:
        image: lsioarmhf/sonarr
        ports:
            - '8989:8989/tcp'
        volumes:
            - 'sonarr_config:/config'
            - 'downloads:/downloads'

    # https://hub.docker.com/r/lsioarmhf/radarr
    radarr:
        image: lsioarmhf/radarr
        ports:
            - '7878:7878/tcp'
        volumes:
            - 'radarr_config:/config'
            - 'downloads:/downloads'
